/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: cholm <marvin@42.fr>                       +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2018/03/12 17:12:32 by cholm             #+#    #+#             */
/*   Updated: 2018/05/14 19:03:27 by femaury          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "libftprintf.h"
#include <limits.h>
#include <locale.h>

int		main(void)
{
	int i;
	char *test;

	i = -5;
	setlocale(LC_ALL, "");
	test = "hello";
	ft_printf("ft_printf -->%+010.5d\n", 24);
	printf("printf -->>>>%+010.5d\n", 24);
	ft_printf("ft_printf ->>%d\n", -7);
	printf("printf ->>>>>%d\n", -7);
	ft_printf("ft_printf ->>%5d\n", 0);
	printf("printf ->>>>>%5d\n", 0);
	ft_printf("ft_printf ->>%5d\n", -7);
	printf("printf ->>>>>%5d\n", -7);
	ft_printf("ft_printf ->>%5d\n", 1560133635);
	printf("printf ->>>>>%5d\n", 1560133635);
	ft_printf("ft_printf ->>%d\n", -2035065302);
	printf("printf ->>>>>%d\n", -2035065302);
	ft_printf("ft_printf ->>%-5d\n", 0);
	printf("printf ->>>>>%-5d\n", 0);
	ft_printf("ft_printf ->>%-5d\n", -7);
	printf("printf ->>>>>%-5d\n", -7);
	ft_printf("ft_printf ->>%-5d\n", 1560133635);
	printf("printf ->>>>>%-5d\n", 1560133635);
	ft_printf("ft_printf ->>%05d\n", 0);
	printf("printf ->>>>>%05d\n", 0);
	ft_printf("ft_printf ->>%05d\n", -7);
	printf("printf ->>>>>%05d\n", -7);
	ft_printf("ft_printf ->>%05d\n", 1560133635);
	printf("printf ->>>>>%05d\n", 1560133635);
	ft_printf("ft_printf ->>%05d\n", -2035065302);
	printf("printf ->>>>>%05d\n", -2035065302);
	ft_printf("ft_printf ->>%+5d\n", 0);
	printf("printf ->>>>>%+5d\n", 0);
	ft_printf("ft_printf ->>%+5d\n", -7);
	printf("printf ->>>>>%+5d\n", -7);
	ft_printf("ft_printf ->>%+5d\n", 1560133635);
	printf("printf ->>>>>%+5d\n", 1560133635);
	ft_printf("ft_printf ->>%+5d\n", -2035065302);
	printf("printf ->>>>>%+5d\n", -2035065302);
	ft_printf("ft_printf ->>%+-5d\n", 0);
	printf("printf ->>>>>%+-5d\n", 0);
	ft_printf("ft_printf ->>%+-5d\n", -7);
	printf("printf ->>>>>%+-5d\n", -7);
	ft_printf("ft_printf ->>%+-5d\n", +1560133635);
	printf("printf ->>>>>%+-5d\n", +1560133635);
	ft_printf("ft_printf ->>%+-5d\n", -2035065302);
	printf("printf ->>>>>%+-5d\n", -2035065302);
	ft_printf("ft_printf ->>% -5d\n", 30);
	printf("printf ->>>>>% -5d\n", 30);
	ft_printf("ft_printf ->>% -5d\n", -7);
	printf("printf ->>>>>% -5d\n", -7);
	ft_printf("ft_printf ->>% -5d\n", 1560133635);
	printf("printf ->>>>>% -5d\n", 1560133635);
	ft_printf("ft_printf ->>% -5d\n", -2035065302);
	printf("printf ->>>>>% -5d\n", -2035065302);
	ft_printf("ft_printf ->>% 05d\n", 0);
	printf("printf ->>>>>% 05d\n", 0);
	ft_printf("ft_printf ->>% 05d\n", -7);
	printf("printf ->>>>>% 05d\n", -7);
	ft_printf("ft_printf ->>% 05d\n", 1560133635);
	printf("printf ->>>>>% 05d\n", 1560133635);
	ft_printf("ft_printf ->>% 05d\n", -2035065302);
	printf("printf ->>>>>% 05d\n", -2035065302);
	ft_printf("ft_printf ->>%+05d\n", 0);
	printf("printf ->>>>>%+05d\n", 0);
	ft_printf("ft_printf ->>%+05d\n", -7);
	printf("printf ->>>>>%+05d\n", -7);
	ft_printf("ft_printf ->>%+05d\n", 1560133635);
	printf("printf ->>>>>%+05d\n", 1560133635);
	ft_printf("ft_printf ->>%+05d\n", -2035065302);
	printf("printf ->>>>>%+05d\n", -2035065302);
	ft_printf("ft_printf ->>%5s\n", "");
	printf("printf ->>>>>%5s\n", "");
	ft_printf("ft_printf ->>%5s\n", "a");
	printf("printf ->>>>>%5s\n", "a");
	ft_printf("ft_printf ->>%5s\n", "ab");
	printf("printf ->>>>>%5s\n", "ab");
	ft_printf("ft_printf ->>%5s\n", "abcdefg");
	printf("printf ->>>>>%5s\n", "abcdefg");
	ft_printf("ft_printf ->>%-5s\n", "");
	printf("printf ->>>>>%-5s\n", "");
	ft_printf("ft_printf ->>%-5s\n", "a");
	printf("printf ->>>>>%-5s\n", "a");
	ft_printf("ft_printf ->>%-5s\n", "ab");
	printf("printf ->>>>>%-5s\n", "ab");
	ft_printf("ft_printf ->>%-5s\n", "abcdefg");
	printf("printf ->>>>>%-5s\n", "abcdefg");
	ft_printf("ft_printf ->>%.5d\n", -7);
	printf("printf ->>>>>%.5d\n", -7);
	ft_printf("ft_printf ->>%.5d\n", 0);
	printf("printf ->>>>>%.5d\n", 0);
	ft_printf("ft_printf ->>%.5d\n", 1560133635);
	printf("printf ->>>>>%.5d\n", 1560133635);
	ft_printf("ft_printf ->>%d\n", -2035065302);
	printf("printf ->>>>>%d\n", -2035065302);
	ft_printf("ft_printf ->>%-.5d\n", 0);
	printf("printf ->>>>>%-.5d\n", 0);
	ft_printf("ft_printf ->>%-.5d\n", -7);
	printf("printf ->>>>>%-.5d\n", -7);
	ft_printf("ft_printf ->>%-.5d\n", 1560133635);
	printf("printf ->>>>>%-.5d\n", 1560133635);
	ft_printf("ft_printf ->>%0.5d\n", 0);
	printf("printf ->>>>>%0.5d\n", 0);
	ft_printf("ft_printf ->>%0.5d\n", -7);
	printf("printf ->>>>>%0.5d\n", -7);
	ft_printf("ft_printf ->>%0.5d\n", 1560133635);
	printf("printf ->>>>>%0.5d\n", 1560133635);
	ft_printf("ft_printf ->>%0.5d\n", -2035065);
	printf("printf ->>>>>%0.5d\n", -2035065);
	ft_printf("ft_printf ->>%+.5d\n", 0);
	printf("printf ->>>>>%+.5d\n", 0);
	ft_printf("ft_printf ->>%+.5d\n", -7);
	printf("printf ->>>>>%+.5d\n", -7);
	ft_printf("ft_printf ->>%+.5d\n", 1560133635);
	printf("printf ->>>>>%+.5d\n", 1560133635);
	ft_printf("ft_printf ->>%+.5d\n", -2035065302);
	printf("printf ->>>>>%+.5d\n", -2035065302);
	ft_printf("ft_printf ->>%+-.5d\n", 0);
	printf("printf ->>>>>%+-.5d\n", 0);
	ft_printf("ft_printf ->>%+-.5d\n", -7);
	printf("printf ->>>>>%+-.5d\n", -7);
	ft_printf("ft_printf ->>%+-.5d\n", 1560133635);
	printf("printf ->>>>>%+-.5d\n", 1560133635);
	ft_printf("ft_printf ->>%+-.5d\n", -2035065302);
	printf("printf ->>>>>%+-.5d\n", -2035065302);
	ft_printf("ft_printf ->>% -.5d\n", 30);
	printf("printf ->>>>>% -.5d\n", 30);
	ft_printf("ft_printf ->>% -.5d\n", -7);
	printf("printf ->>>>>% -.5d\n", -7);
	ft_printf("ft_printf ->>% -.5d\n", 1560133635);
	printf("printf ->>>>>% -.5d\n", 1560133635);
	ft_printf("ft_printf ->>% -.5d\n", -2035065302);
	printf("printf ->>>>>% -.5d\n", -2035065302);
	ft_printf("ft_printf ->>% 0.5d\n", 0);
	printf("printf ->>>>>% 0.5d\n", 0);
	ft_printf("ft_printf ->>% 0.5d\n", -7);
	printf("printf ->>>>>% 0.5d\n", -7);
	ft_printf("ft_printf ->>% 0.5d\n", 1560133635);
	printf("printf ->>>>>% 0.5d\n", 1560133635);
	ft_printf("ft_printf ->>% 0.5d\n", -2035065302);
	printf("printf ->>>>>% 0.5d\n", -2035065302);
	ft_printf("ft_printf ->>%+0.5d\n", 0);
	printf("printf ->>>>>%+0.5d\n", 0);
	ft_printf("ft_printf ->>%+0.5d\n", -7);
	printf("printf ->>>>>%+0.5d\n", -7);
	ft_printf("ft_printf ->>%+0.5d\n", 1560133635);
	printf("printf ->>>>>%+0.5d\n", 1560133635);
	ft_printf("ft_printf ->>%+0.5d\n", -2035065302);
	printf("printf ->>>>>%+0.5d\n", -2035065302);
	ft_printf("ft_printf ->>%010.5d\n", 7);
	printf("printf ->>>>>%010.5d\n", 7);
	ft_printf("ft_printf ->>%-10.5d\n", -42);
	printf("printf ->>>>>%-10.5d\n", -42);
	ft_printf("ft_printf ->>%+020.5d\n", 1560133635);
	printf("printf ->>>>>%+020.5d\n", 1560133635);
	ft_printf("ft_printf ->>%+010.5d\n", -2035065302);
	printf("printf ->>>>>%+010.5d\n", -2035065302);
	ft_printf("ft_printf ->>%.5s\n", "");
	printf("printf ->>>>>%.5s\n", "");
	ft_printf("ft_printf ->>%.5s\n", "a");
	printf("printf ->>>>>%.5s\n", "a");
	ft_printf("ft_printf ->>%.5s\n", "ab");
	printf("printf ->>>>>%.5s\n", "ab");
	ft_printf("ft_printf ->>je suis %15s et moi %10s\n", "abcdefg", "efghij");
	printf("printf ->>>>>je suis %15s et moi %10s\n", "abcdefg", "efghij");
	ft_printf("ft_printf ->>%-5s\n", "");
	printf("printf ->>>>>%-5s\n", "");
	ft_printf("ft_printf ->>%-5s\n", "a");
	printf("printf ->>>>>%-5s\n", "a");
	ft_printf("ft_printf ->>%5s\n", "abcdefghijkl");
	printf("printf ->>>>>%5s\n", "abcdefghijkl");	
	ft_printf("ft_printf ->>%010.5O\n", 50);
	printf("printf ->>>>>%010.5O\n", 50);
	ft_printf("ft_printf ->>%010.5d\n", 50);
	printf("printf ->>>>>%010.5d\n", 50);
	ft_printf("ft_printf ->>%#10o\n", 42);
	printf("printf ->>>>>%#10o\n", 42);
	ft_printf("ft_printf ->>%010.5u\n", 50);
	printf("printf ->>>>>%010.5u\n", 50);
	ft_printf("ft_printf ->>%010.5x\n", 1525);
	printf("printf ->>>>>%010.5x\n", 1525);
	ft_printf("ft_printf ->>%#10x\n", 42);
	printf("printf ->>>>>%#10x\n", 42);
	ft_printf("ft_printf ->>%010i\n", -1525);
	printf("printf ->>>>>%010i\n", -1525);
	ft_printf("ft_printf ->>% +d\n", 42);
	printf("printf ->>>>>% +d\n", 42);
	ft_printf("ft_printf ->>%c\n", 42);
	ft_printf("printf ->>>>>%c\n", 42);
	printf("printf ->>>>>%c\n", 42);
	ft_printf("ft_printf ->>%-05s\n", "a");
	printf("printf ->>>>>%-05s\n", "a");
	ft_printf("ft_printf ->>%S\n", L"我是一只猫");
	printf("printf ->>>>>%S\n", L"我是一只猫");
	ft_printf("ft_printf ->>%hd\n", 32768);
	printf("printf ->>%hd\n", 32768);
	ft_printf("ft_printf ->>%hhd\n", 128);
	printf("printf ->>%hhd\n", 128);
	ft_printf("ft_printf ->>%ld\n", -2147483648);
	printf("printf ->>%ld\n", -2147483648);
	ft_printf("ft_printf ->>%ld\n", 2147483648);
	printf("printf ->>%ld\n", 2147483648);
	ft_printf("ft_printf ->>%llx\n", 9223372036854775808);
	printf("printf ->>%llx\n", 9223372036854775808);
	ft_printf("-->@moulitest: %.d<--\n", 0);
	printf("-->@moulitest: %.d<--\n", 0);
	ft_printf("ft_printf ->>%c\n", 42);
	printf("printf ->>>>>%c\n", 42);
	ft_printf("ft_printf ->>%5c\n", 42);
	printf("printf ->>>>>%5c\n", 42);
	ft_printf("ft_printf ->>%%\n");
	printf("printf ->>>>>%%\n");
	ft_printf("ft_printf ->>%5%\n");
	printf("printf ->>>>>%5%\n");
	ft_printf("ft_printf ->>%.0%\n");
	printf("printf ->>>>>%.0%\n");
	ft_printf("ft_printf ->>%     %\n", "test");
	printf("printf ->>>>>%     %\n", "test");
	ft_printf("ft_printf ->>%jx\n", 4294967296);
	printf("printf ->>>>>%jx\n", 4294967296);
	ft_printf("ft_printf ->>%#8x\n", 42);
	printf("printf ->>>>>%#8x\n", 42);
	ft_printf("ft_printf ->>%#08x\n", 42);
	printf("printf ->>>>>%#08x\n", 42);
	ft_printf("ft_printf ->>%#-08x\n", 42);
	printf("printf ->>>>>%#-08x\n", 42);
	ft_printf("ft_printf ->>%llX\n", 4294967296);
	printf("printf ->>>>>%llX\n", 4294967296);
	ft_printf("ft_printf ->>%lld\n", 9223372036854775807);
	printf("printf ->>>>>%lld\n", 9223372036854775807);
	ft_printf("ft_printf ->>%.2s is a string\n", "this");
	printf("printf ->>>>>%.2s is a string\n", "this");
	ft_printf("ft_printf ->>%5.2s is a string\n", "this");
	printf("printf ->>>>>%5.2s is a string\n", "this");
	ft_printf("ft_printf ->>@moulitest: %s\n", NULL);
	printf("printf ->>>>>@moulitest: %s\n", NULL);
	ft_printf("ft_printf ->>@moulitest: %c\n", 0);
	printf("printf ->>>>>@moulitest: %c\n", 0);
	ft_printf("ft_printf ->>%U\n", 4294967296);
	printf("printf ->>>>>%U\n", 4294967296);
	ft_printf("ft_printf ->>%hU\n", 4294967296);
	printf("printf ->>>>>%hU\n", 4294967296);
	ft_printf("ft_printf ->>@moulitest: %#.x\n", 0);
	printf("printf ->>>>>@moulitest: %#.x\n", 0);
	ft_printf("ft_printf ->>@moulitest: %#.o %#.0o\n", 0, 0);
	printf("printf ->>>>>@moulitest: %#.o %#.0o\n", 0, 0);
	ft_printf("ft_printf ->>@moulitest: %#.o\n", 0);
	printf("printf ->>>>>@moulitest: %#.o\n", 0);
	ft_printf("ft_printf ->>%lld\n", -9223372036854775808);
	printf("printf ->>>>>%lld\n", -9223372036854775808);
	ft_printf("ft_printf ->>@moulitest: %.d %.0d\n", 42, 43);
	printf("printf ->>>>>@moulitest: %.d %.0d\n", 42, 43);
	ft_printf("ft_printf ->>@moulitest: %.d\n", 42);
	printf("printf ->>>>>@moulitest: %.d\n", 42);
	ft_printf("ft_printf ->>{%}\n");
	printf("printf ->>>>>{%}\n");
	ft_printf("ft_printf ->>%p\n", &i);
	printf("printf ->>>>>%p\n", &i);
	ft_printf("ft_printf ->>%D\n", 0L);
	printf("printf ->>>>>%D\n", 0L);
	ft_printf("ft_printf ->>%D\n", -1L);
	printf("printf ->>>>>%D\n", -1L);
	ft_printf("ft_printf ->>% Zoooo\n");
	printf("printf ->>>>>% Zoooo\n");
	ft_printf("ft_printf ->>%hhO, %hhO\n", 0, USHRT_MAX);
	printf("printf ->>>>>%hhO, %hhO\n", 0, USHRT_MAX);
	ft_printf("ft_printf ->>%o, %ho, %hho\n", -42, -42, -42);
	printf("printf ->>>>>%o, %ho, %hho\n", -42, -42, -42);
	ft_printf("ft_printf ->>% x|%+x\n", 42, 42);
	printf("printf ->>>>>% x|%+x\n", 42, 42);
	ft_printf("ft_printf ->>% X|%+X\n", 42, 42);
	printf("printf ->>>>>% X|%+X\n", 42, 42);
	ft_printf("ft_printf ->>% o|%+o\n", 42, 42);
	printf("printf ->>>>>% o|%+o\n", 42, 42);
	ft_printf("ft_printf ->>%hhu / %hhu\n", SHRT_MAX - 42,  SHRT_MAX - 4200);
	printf("printf ->>>>>%hhu / %hhu\n", SHRT_MAX - 42,  SHRT_MAX - 4200);
	ft_printf("ft_printf ->>% p %+p\n", 42, 42);
	printf("printf ->>>>>% p %+p\n", 42, 42);
	ft_printf("ft_printf ->>%.p, %.0p\n", 0, 0);
	printf("printf ->>>>>%.p, %.0p\n", 0, 0);
	ft_printf("ft_printf ->>%p\n", 0);
	printf("printf ->>>>>%p\n", 0);
	ft_printf("ft_printf ->>{%05.c}\n", 0);
	printf("printf ->>>>>{%05.c}\n", 0);
	ft_printf("ft_printf ->>%.p, %p\n", 0, 0);
	printf("printf ->>>>>%.p, %p\n", 0, 0);
	ft_printf("ft_printf ->>%.5p\n", 0);
	printf("printf ->>>>>%.5p\n", 0);
	ft_printf("ft_printf ->>%9.2p\n", 1234);
	printf("printf ->>>>>%9.2p\n", 1234);
	ft_printf("ft_printf ->>%2.9p\n", 1234);
	printf("printf ->>>>>%2.9p\n", 1234);
	ft_printf("ft_printf ->>%.5c\n", 42);
	printf("printf ->>>>>%.5c\n", 42);
	ft_printf("ft_printf ->>%.5C\n", 42);
	printf("printf ->>>>>%.5C\n", 42);
	ft_printf("ft_printf ->>{% c}\n", 'a');
	printf("printf ->>>>>{% c}\n", 'a');
	ft_printf("ft_printf ->>{% C}\n", L'a');
	printf("printf ->>>>>{% C}\n", L'a');
	ft_printf("ft_printf ->>{% S}\n", L"(carl)");
	printf("printf ->>>>>{% S}\n", L"(carl)");
	ft_printf("ft_printf ->>%+o\n", 0);
	printf("printf ->>>>>%+o\n", 0);
	ft_printf("ft_printf ->>%#O\n", 1);
	printf("printf ->>>>>%#O\n", 1);
	ft_printf("ft_printf ->>%#X\n", 0);
	printf("printf ->>>>>%#X\n", 0);
	ft_printf("ft_printf ->>{%-15Z}\n", 123);
	printf("printf ->>>>>{%-15Z}\n", 123);
	ft_printf("ft_printf ->>{%03c}\n", 0);
	printf("printf ->>>>>{%03c}\n", 0);
	ft_printf("ft_printf ->>{%05s}\n", "abc");
	printf("printf ->>>>>{%05s}\n", "abc");
	ft_printf("ft_printf ->>{%05p}\n", 0);
	printf("printf ->>>>>{%05p}\n", 0);
	ft_printf("ft_printf ->>{%10R}\n");
	printf("printf ->>>>>{%10R}\n");
	ft_printf("ft_printf ->>%C\n", L'猫');
	printf("printf ->>>>>%C\n", L'猫');
	ft_printf("ft_printf ->>%C\n", L'Ĝ');
	printf("printf ->>>>>%C\n", L'Ĝ');
	ft_printf("ft_printf ->>%C\n", 'c');
	printf("printf ->>>>>%C\n", 'c');
	ft_printf("ft_printf ->>%C\n", L'Ɏ');
	printf("printf ->>>>>%C\n", L'Ɏ');
	ft_printf("ft_printf ->>%C%C\n", '4', '2');
	printf("printf ->>>>>%C%C\n", '4', '2');
	ft_printf("ft_printf ->>%C\n", 0);
	printf("printf ->>>>>%C\n", 0);
	ft_printf("ft_printf ->>%lc, %lc\n", L'暖', L'ح');
	printf("printf ->>>>>%lc, %lc\n", L'暖', L'ح');
	ft_printf("ft_printf ->>%S\n", L"米");
	printf("printf ->>>>>%S\n", L"米");
	ft_printf("ft_printf ->>%S\n", L"我是一只猫。");
	printf("printf ->>>>>%S\n", L"我是一只猫。");
	ft_printf("ft_printf ->>{%S}\n", NULL);
	printf("printf ->>>>>{%S}\n", NULL);
	ft_printf("ft_printf ->>%S\n", L"暖炉");
	printf("printf -*****%S\n", L"暖炉");
	ft_printf("ft_printf ->>{%30S}\n", L"我是一只猫。");
	printf("printf ->>>>>{%30S}\n", L"我是一只猫。");
	ft_printf("ft_printf ->>{% S}\n", L"(null)");
	printf("printf ->>>>>{% S}\n", L"(null)");
	ft_printf("ft_printf ->>{%S}\n", L"n");
	printf("printf ->>>>>{%S}\n", L"n");
	ft_printf("ft_printf ->>%4.15s\n", "42");
	printf("printf ->>>>>%4.15s\n", "42");
	ft_printf("ft_printf ->>%D\n", -1L);
	printf("printf ->>>>>%D\n", -1L);
	ft_printf("ft_printf ->>%D\n", LONG_MIN);
	printf("printf ->>>>>%D\n", LONG_MIN);
	ft_printf("ft_printf ->>%hD, %hD\n", 0, USHRT_MAX);
	printf("printf ->>>>>%hD, %hD\n", 0, USHRT_MAX);
	ft_printf("ft_printf ->>%hhD, %hhD\n", 0, USHRT_MAX);
	printf("printf ->>>>>%hhD, %hhD\n", 0, USHRT_MAX);
	ft_printf("ft_printf ->>%.0d, %.d\n", 25, 25);
	printf("printf ->>>>>%.0d, %.d\n", 25, 25);
	ft_printf("ft_printf ->>%.0p, %.p\n", 0, 0);
	printf("printf ->>>>>%.0p, %.p\n", 0, 0);
	ft_printf("ft_printf ->>%o, %ho, %hho\n", -42, -42, -42);
	printf("printf ->>>>>%o, %ho, %hho\n", -42, -42, -42);
	ft_printf("ft_printf ->>{%05.c}\n", 0);
	printf("printf ->>>>>{%05.c}\n", 0);
	ft_printf("ft_printf ->>{%05.%}\n", 0);
	printf("printf ->>>>>{%05.%}\n", 0);
	ft_printf("ft_printf ->>{%05.Z}\n", 0);
	printf("printf ->>>>>{%05.Z}\n", 0);
	ft_printf("ft_printf ->>{%#.5x}\n", 1);
	printf("printf ->>>>>{%#.5x}\n", 1);
	ft_printf("ft_printf ->>{%05.S}\n", L"42 c est cool");
	printf("printf ->>>>>{%05.S}\n", L"42 c est cool");
	ft_printf("ft_printf ->>% h\n");
	printf("printf ->>>>>% h\n");
	ft_printf("ft_printf -->%+010.5d\n", 24);
	printf("printf -->>>>%+010.5d\n", 24);
	ft_printf("ft_printf -->{%030d}\n", 10000);
	printf("printf -->>>>{%030d}\n", 10000);
	ft_printf("ft_printf -->{%010d}\n", -42);
	printf("printf -->>>>{%010d}\n", -42);
	ft_printf("ft_printf -->{%030x}\n", 0xFFFF);
	printf("printf -->>>>{%030x}\n", 0xFFFF);
	ft_printf("ft_printf ->>%+04d\n", 42);
	printf("printf ->>>>>%+04d\n", 42);



	


	return (0);
}
